### ISSUE TITLE
Missing Updater_Signing.h header patch

### ISSUE THREAD

**Issue by maribeiro** [heeeyflo/esp8266-platformio-signed-ota#1]
According to signing.py , the header should also be patched to include the public key.
If you you arduino you'll see that it first uses signing.py --mode header with public key (to patch updater_signing.h) and then uses signing.py --mode sign with private key (to sign the bin file)

**Comment by heeeyflo** [comment]
Howdy, @maribeiro 

If I understood you correctly, you mentioned just one of the possible ways how to initialize OTA signature verification. Accordingly to [OTA readme](https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.rst), `signing.py --mode=header` intended to be used by Arduino IDE to make almost the same thing, as I'm done manually in my `src/main.ino` — add a public key to `signing_pubkey[]` constant and set `#define ARDUINO_SIGNING 1`.

This constant and define are further used by the [cores/esp8266/Updater.cpp](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Updater.cpp), which does pretty the same initialization on L15, L16, and L43, so there is no functional difference.

Although you right, the way you described is more conventional. I will replace manual initialization in `src/main.ino` with `ARDUINO_SIGNING` & `signing_pubkey[]` way soon.

Thank you :sparkles:

**Comment by maribeiro** [comment]
Hi @imcatwhocode,
That's correct. Documenation on esp8266 side is a bit scarce regarding signing process.
Thanks for taking your time giving the explanation.
I'll close this.
